Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    config.vm.provision :shell, :inline => $PROVISION_SCRIPT

    config.vm.synced_folder "./mirror", "/home/vagrant/host-mirror"

    config.vm.provider "vmware_desktop" do |vb|
        vb.memory = "2048"
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        # vb.gui = true
    end
end

$PROVISION_SCRIPT = <<EOF
    if [ -f "/var/vagrant_provision" ]; then
        exit 0
    fi

    # Notice that `sudo` is used here throughout

    set -x -e     # verbose output, stop on any error
   
    sudo apt-get install build-essential software-properties-common -y 
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    sudo apt-get update -y

    sudo apt-get install -y gcc-9 > /dev/null 2>&1
    sudo apt-get install -y g++-9 > /dev/null 2>&1

    sudo apt-get install -y valgrind > /dev/null 2>&1
    sudo apt-get install -y gdb > /dev/null 2>&1

    sudo apt-get install -y python3.7 > /dev/null 2>&1
    sudo apt-get install -y python-pytest > /dev/null 2>&1
    sudo apt-get install -y tree > /dev/null 2>&1
    sudo apt-get install -y unzip > /dev/null 2>&1

    sudo update-alternatives --install /usr/bin/python \
        python /usr/bin/python2.7 10
    sudo update-alternatives --install /usr/bin/python \
        python /usr/bin/python3.7 20

    sudo update-alternatives --install /usr/bin/gcc \
        gcc /usr/bin/gcc-7 20
    sudo update-alternatives --install /usr/bin/gcc \
        gcc /usr/bin/gcc-9 30

    sudo apt install -y python3-pip > /dev/null 2>&1
    
    pip3 install numpy
    pip3 install networkx
    pip3 install pandas
    pip3 install retworkx
    pip3 install sympy

    python3 -m pip install --upgrade pip
    python3 -m pip install --upgrade pillow
    python3 -m pip install -U matplotlib

    touch /var/vagrant_provision
EOF

